### ISSUE TITLE
Doesn't use IntelliJ's default browser

### ISSUE THREAD

**Issue by kayler-renslow** [gejun123456/IntellijGoToStackOverFlow#1]
When I click the "search stackoverflow" button, it always opens in Chromium, rather than my default browser (Google Chrome, which isn't Chromium).

I looked into your source code, and I suggest using `com.intellij.ide.BrowserUtil.browse(String url)` instead of `com.intellij.ide.browsers.BrowserLauncher`. Although technically `BrowserUtil` uses `BrowserLauncher`, `BrowserUtil` selects the default browser.

**Comment by gejun123456** [comment]
thanks,  will do it today.

**Comment by gejun123456** [comment]
fixed, you can download it https://github.com/gejun123456/IntellijGoToStackOverFlow/releases/download/v1.1/stackoverflow-1.1.zip
if it can't work, please tell me. thanks.

**Comment by kayler-renslow** [comment]
Can you update it on your repository on plugins.jetbrains.com please? Thanks.

**Comment by gejun123456** [comment]
already updated, jetbrain need two day to review.😁

**Comment by kayler-renslow** [comment]
appears to be in working order.
